spring:
  mail:
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
spreadSheet:
  urlOfNBA: ${URL_NBA}
  urlOfSIAP: ${URL_SIAP}
  urlOfCHALLENGER: ${URL_CHALLENGER}
  urlOfSPE: ${URL_SPE}

mailStructure:
  receiver: ${MAIL_RECEIVER}
  sender: ${MAIL_USERNAME}