version: '3.7'
services:
  parsing-to-excel-service:
    container_name: parsing-to-excel-service
    build:
      context: ../
      dockerfile: ./docker/parsing-to-excel-service/Dockerfile
    image: parsing-excel-service:latest
    ports:
      - "8080:8080"
    environment:
      MAIL_USERNAME: fixme
      MAIL_PASSWORD: fixme
      MAIL_RECEIVER: fixme

      URL_NBA: fixme
      URL_SIAP: fixme
      URL_CHALLENGER: fixme
      URL_SPE: fixme